---
- name: Install system dependencies
  package:
    name: "{{ item }}"
    state: present
  register: _dependencies_install
  retries: 2
  until: _dependencies_install | success
  with_items: "{{ docker_dependencies }}"

- name: Remove old versions
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - lxc-docker
    - docker-engine

- name: Install docker
  package:
    name: "{{ docker_package | default('docker-ce') }}"
    state: present
    update_cache: yes
  register: __ret
  retries: 10
  until: __ret is succeeded
  notify:
    - restart docker

- name: ensure docker-py module is installed
  pip:
    name: docker-py
    version: 1.9.0
  when: dockerpy


